### ISSUE TITLE
BioModel Discussion Issue for eos4tcc

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos4tcc#5]
**Summary !!!**

- **BioModel Name**: Kim2022 - BayeshERG: A deep learning model for predicting hERG channel blockers

- **BioModel Tag**: Machine learning model, Ersilia, FAIR AIML

- **Metadata Comments**: 
BayeshERG is a predictor of small molecule-induced blockade of the hERG ion channel.

- **Contributor**:
> 
 | roles             | Names | 
 | :---------------- | :------: | 
 | Curator        |   @Zainab-ik   | 
 | Code contributor      |   @azycn       | 
 | Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated

- **Annotation file**: [here](https://docs.google.com/spreadsheets/d/14j0yn8BJwzXkJbwnT4n_PhWMZPmg8FW4a8Qf_LHeyQ/edit?usp=sharing)

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

Is this model on the pending to do list? Do you have any specific questions?

**Comment by Zainab-ik** [comment]
> Hi @Zainab-ik
> 
> Is this model on the pending to do list? Do you have any specific questions?

Hi @GemmaTuron 
It's on pending list, and the annotation is complete. It was done by one of the Hackathon participant. I just completed the merging with mine. Kindly review. 

Sorry for the late response.

**Comment by GemmaTuron** [comment]
okay!

This looks good. @Zainab-ik could you copy the Annotation Files completed from the Hackathon folder to the metadata folder and rename them with the eos identifier for comprehensiveness with the rest of the models?

Thanks!

**Comment by Zainab-ik** [comment]
> okay!
> 
> This looks good. @Zainab-ik could you copy the Annotation Files completed from the Hackathon folder to the metadata folder and rename them with the eos identifier for comprehensiveness with the rest of the models?
>
The annotation files has been uploaded to the metadata folder with their respective identifier. 
> Thanks!
